const users = [
  {
    id: "410544b2-4001-4271-9855-fec4b6a6442a",
    name: "test",
    email: "test@test.com",
    password: "123456",
  },
]

const clients = [
  {
    id: "3958dc9e-712f-4377-85e9-fec4b6a6442a",
    name: "Delba de Oliveira",
    email: "delba@oliveira.com",
  },
  {
    id: "3958dc9e-742f-4377-85e9-fec4b6a6442a",
    name: "Lee Robinson",
    email: "lee@robinson.com",
  },
  {
    id: "3958dc9e-737f-4377-85e9-fec4b6a6442a",
    name: "Hector Simpson",
    email: "hector@simpson.com",
  },
  {
    id: "50ca3e18-62cd-11ee-8c99-0242ac120002",
    name: "Steven Tey",
    email: "steven@tey.com",
  },
  {
    id: "3958dc9e-787f-4377-85e9-fec4b6a6442a",
    name: "Steph Dietz",
    email: "steph@dietz.com",
  },
  {
    id: "76d65c26-f784-44a2-ac19-586678f7c2f2",
    name: "Michael Novotny",
    email: "michael@novotny.com",
  },
  {
    id: "d6e15727-9fe1-4961-8c5b-ea44a9bd81aa",
    name: "Evil Rabbit",
    email: "evil@rabbit.com",
  },
  {
    id: "126eed9c-c90c-4ef6-a4a8-fcf7408d3c66",
    name: "Emil Kowalski",
    email: "emil@kowalski.com",
  },
  {
    id: "CC27C14A-0ACF-4F4A-A6C9-D45682C144B9",
    name: "Amy Burns",
    email: "amy@burns.com",
  },
  {
    id: "13D07535-C59E-4157-A011-F8D2EF4E0CBB",
    name: "Balazs Orban",
    email: "balazs@orban.com",
  },
]

const evaluations = [
  {
    customer_id: customers[0].id,
    amount: 15795,
    status: "pending",
    date: "2022-12-06",
    appels: [
      {
        appel: 1,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
      {
        appel: 2,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
    ],
  },
  {
    customer_id: customers[1].id,
    amount: 20348,
    status: "pending",
    date: "2022-11-14",
    appel: [
      {
        appel: 1,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
      {
        appel: 2,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
    ],
  },
  {
    customer_id: customers[4].id,
    amount: 3040,
    status: "done",
    date: "2022-10-29",
    appels: [
      {
        appel: 1,
        contact_client: 3,
        accueil_client: 3,
        ecoute_client: 4,
        reformulation: 3,
        argumentation: 5,
        conclusion: 3,
      },
      {
        appel: 2,
        contact_client: 4,
        accueil_client: 4,
        ecoute_client: 3,
        reformulation: 4,
        argumentation: 4,
        conclusion: 4,
      },
    ],
  },
  {
    customer_id: customers[3].id,
    amount: 44800,
    status: "done",
    date: "2023-09-10",
    appels: [
      {
        appel: 1,
        contact_client: 3,
        accueil_client: 3,
        ecoute_client: 4,
        reformulation: 3,
        argumentation: 5,
        conclusion: 3,
      },
      {
        appel: 2,
        contact_client: 4,
        accueil_client: 4,
        ecoute_client: 3,
        reformulation: 4,
        argumentation: 4,
        conclusion: 4,
      },
    ],
  },
  {
    customer_id: customers[5].id,
    amount: 34577,
    status: "pending",
    date: "2023-08-05",
    appels: [
      {
        appel: 1,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
      {
        appel: 2,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
    ],
  },
  {
    customer_id: customers[7].id,
    amount: 54246,
    status: "pending",
    date: "2023-07-16",
    appels: [
      {
        appel: 1,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
      {
        appel: 2,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
    ],
  },
  {
    customer_id: customers[6].id,
    amount: 666,
    status: "pending",
    date: "2023-06-27",
    appels: [
      {
        appel: 1,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
      {
        appel: 2,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
    ],
  },
  {
    customer_id: customers[3].id,
    amount: 32545,
    status: "done",
    date: "2023-06-09",
    appels: [
      {
        appel: 1,
        contact_client: 3,
        accueil_client: 3,
        ecoute_client: 4,
        reformulation: 3,
        argumentation: 5,
        conclusion: 3,
      },
      {
        appel: 2,
        contact_client: 4,
        accueil_client: 4,
        ecoute_client: 3,
        reformulation: 4,
        argumentation: 4,
        conclusion: 4,
      },
    ],
  },
  {
    customer_id: customers[4].id,
    amount: 1250,
    status: "done",
    date: "2023-06-17",
    appels: [
      {
        appel: 1,
        contact_client: 3,
        accueil_client: 3,
        ecoute_client: 4,
        reformulation: 3,
        argumentation: 5,
        conclusion: 3,
      },
      {
        appel: 2,
        contact_client: 4,
        accueil_client: 4,
        ecoute_client: 3,
        reformulation: 4,
        argumentation: 4,
        conclusion: 4,
      },
    ],
  },
  {
    customer_id: customers[5].id,
    amount: 8546,
    status: "done",
    date: "2023-06-07",
    appels: [
      {
        appel: 1,
        contact_client: 3,
        accueil_client: 3,
        ecoute_client: 4,
        reformulation: 3,
        argumentation: 5,
        conclusion: 3,
      },
      {
        appel: 2,
        contact_client: 4,
        accueil_client: 4,
        ecoute_client: 3,
        reformulation: 4,
        argumentation: 4,
        conclusion: 4,
      },
    ],
  },
  {
    customer_id: customers[1].id,
    amount: 500,
    status: "done",
    date: "2023-08-19",
    appels: [
      {
        appel: 1,
        contact_client: 3,
        accueil_client: 3,
        ecoute_client: 4,
        reformulation: 3,
        argumentation: 5,
        conclusion: 3,
      },
      {
        appel: 2,
        contact_client: 4,
        accueil_client: 4,
        ecoute_client: 3,
        reformulation: 4,
        argumentation: 4,
        conclusion: 4,
      },
    ],
  },
  {
    customer_id: customers[5].id,
    amount: 8945,
    status: "pending",
    date: "2023-06-03",
    appels: [
      {
        appel: 1,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
      {
        appel: 2,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
    ],
  },
  {
    customer_id: customers[2].id,
    amount: 8945,
    status: "pending",
    date: "2023-06-18",
    appels: [
      {
        appel: 1,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
      {
        appel: 2,
        contact_client: 0,
        accueil_client: 0,
        ecoute_client: 0,
        reformulation: 0,
        argumentation: 0,
        conclusion: 0,
      },
    ],
  },
  {
    customer_id: customers[0].id,
    amount: 8945,
    status: "done",
    date: "2023-10-04",
    appels: [
      {
        appel: 1,
        contact_client: 3,
        accueil_client: 3,
        ecoute_client: 4,
        reformulation: 3,
        argumentation: 5,
        conclusion: 3,
      },
      {
        appel: 2,
        contact_client: 4,
        accueil_client: 4,
        ecoute_client: 3,
        reformulation: 4,
        argumentation: 4,
        conclusion: 4,
      },
    ],
  },
  {
    customer_id: customers[2].id,
    amount: 1000,
    status: "done",
    date: "2022-06-05",
    appels: [
      {
        appel: 1,
        contact_client: 3,
        accueil_client: 3,
        ecoute_client: 4,
        reformulation: 3,
        argumentation: 5,
        conclusion: 3,
      },
      {
        appel: 2,
        contact_client: 4,
        accueil_client: 4,
        ecoute_client: 3,
        reformulation: 4,
        argumentation: 4,
        conclusion: 4,
      },
    ],
  },
]

module.exports = {
  users,
  customers,
  revenue,
}
